# Generated by Django 3.0.5 on 2020-04-16 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=60)),
                ('last_name', models.CharField(default='none', max_length=60)),
                ('language', models.CharField(default='none', max_length=60)),
                ('date_of_birth', models.DateField(default=datetime.date(1111, 11, 11), max_length=8)),
                ('busy', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('business_name', models.CharField(default='none', max_length=60)),
                ('business_type', models.CharField(default='none', max_length=60)),
                ('description', models.TextField(default='none', max_length=350)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
