# Generated by Django 3.0.5 on 2020-04-16 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1), max_length=8),
        ),
    ]
