# Generated by Django 3.0.5 on 2020-04-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
