# Generated by Django 3.0.5 on 2020-04-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200418_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='evaluated',
        ),
    ]
