# Generated by Django 3.0.5 on 2020-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
