# Generated by Django 3.0.5 on 2020-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-blank.png', upload_to='profile_pics'),
        ),
    ]
