# Generated by Django 3.0.5 on 2020-05-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200429_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_offers',
            field=models.CharField(blank=True, default='none', max_length=5000),
        ),
    ]
