# Generated by Django 3.0.5 on 2020-05-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_job_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_offers',
        ),
    ]
