# Generated by Django 3.0.5 on 2020-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_job_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post',
            field=models.BooleanField(default=False),
        ),
    ]
