# Generated by Django 3.0.5 on 2020-07-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_can_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_post',
            field=models.BooleanField(default=True),
        ),
    ]
