# Generated by Django 3.0.5 on 2020-09-16 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_auto_20200916_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerbiases',
            name='length',
        ),
        migrations.CreateModel(
            name='ManagerPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_list_order', models.CharField(default='none', max_length=500)),
                ('length', models.IntegerField(default=0)),
                ('post_per_day', models.IntegerField(default=0)),
                ('instagram', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
