# Generated by Django 3.0.5 on 2020-09-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200916_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpreference',
            name='manager',
        ),
        migrations.DeleteModel(
            name='ManagerBiases',
        ),
        migrations.DeleteModel(
            name='ManagerPreference',
        ),
    ]
