# Generated by Django 3.0.5 on 2020-10-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_managerpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerPreference',
        ),
    ]
